### ISSUE TITLE
Filenames are truncated when deeply nested in workspace

### ISSUE THREAD

**Issue by mgmeyers** [svsool/vscode-memo#141]
This isn't so much of an issue with this plugin as a limitation of vscode, but I've been noticing it's difficult to tell which file the completion menu is showing me when files are nested deeply (or have a long name):

<img width="561" alt="_Extension_Development_Host__-_Visual_Studio_Code_and_Visual_Studio_Code" src="https://user-images.githubusercontent.com/2694747/94996080-4aca5600-0557-11eb-814f-8722fcbe5636.png">

I was playing around with some fixes here, and found two that seemed reasonable in use.

## 1. Use `shortRef` as the label with `longRef` as the `item.detail`:

```javascript
const item = new CompletionItem(shortRef, CompletionItemKind.File);
item.detail = longRef;
```

<img width="536" alt="_Extension_Development_Host__-_Visual_Studio_Code_and_New_Issue_·_svsool_vscode-memo" src="https://user-images.githubusercontent.com/2694747/94996151-b8768200-0557-11eb-893a-821111b3cde3.png">

`item.detail` can be expanded:

<img width="681" alt="_Extension_Development_Host__-_Visual_Studio_Code_and_New_Issue_·_svsool_vscode-memo" src="https://user-images.githubusercontent.com/2694747/94996241-32a70680-0558-11eb-842c-70bb223cdb7d.png">

The problem with this approach is you can't search the file path.

## 2. Reverse the `longRef` path

```javascript
const label = longRef.split(path.sep).reverse().join(path.sep);
const item = new CompletionItem(label, CompletionItemKind.File);
```

I thought this would be kind of weird to use, but it actually felt the most natural to me. It searches the file names first, then offers a more context specific view of the path without having to expand anything.

<img width="527" alt="_Extension_Development_Host__-_Visual_Studio_Code_and_Visual_Studio_Code" src="https://user-images.githubusercontent.com/2694747/94996322-d7c1df00-0558-11eb-991e-c1e35deb046b.png">

---

Could even have a few options selectable via settings (something like `memo.completion.format`):
- `fullPath`
- `fullPathReversed`
- `filename`

Let me know if you have any thoughts/ideas here, and I can raise a PR!

**Comment by svsool** [comment]
Thanks for looking into this and coming with the suggestions!

We can start with the first option, and it should resolve the problem here. Please ensure that `item.detail` is not shown when `shortRef` === `longRef` because that's possible.

I suggest considering the second option if Memo users will find the first option problematic; otherwise, I think it's good to keep it simple.

**Comment by mgmeyers** [comment]
Hmm, yeah, that's a bit tricky. Another option: we could offer a `depth` setting to control how much of the full path to display.

So with something like `memo.completion.directoryDisplayDepth = 1` we'd get:

```
inbox.md
.../my-folder-1/inbox.md
.../my-folder-2/inbox.md
```

Then, we could still have the full path in the `item.detail`?

**Comment by svsool** [comment]
Looks like suggestions and details are finally going to be resizable https://github.com/microsoft/vscode/issues/29757#issuecomment-716580569, so hopefully no need to solve it via paths truncating. 

Found another interesting [comment](https://github.com/microsoft/vscode/issues/29757) there, perhaps [this](https://marketplace.visualstudio.com/items?itemName=be5invis.vscode-custom-css) extension allows doing css adjustments in a hacky way.

**Comment by svsool** [comment]
Resizing works for me with [VS Code 1.51](https://code.visualstudio.com/updates/v1_51#_resizable-suggestions). I'll close this one for now. Feel free to reopen if something.
